<?xml version="1.0" encoding="utf-8"?>
<!--
    This document contains a variety of XML features
-->
<!DOCTYPE root [
        <!ELEMENT root (element)>
        <!ATTLIST root
                xmlns:prefix CDATA #FIXED "uri:for-prefix">
        <!ELEMENT element (#PCDATA|children)*>
        <!ELEMENT children (#PCDATA)>
        <!ENTITY entity "ENTITY">
        ]>
<root xmlns:prefix="uri:for-prefix">
    <element attribute="value">

        TextNode

        <?processing processing instruction content ?>

        <children>&entity;</children>
        <children><![CDATA[Cdata Node]]></children>
        <children>Plain and <![CDATA[Cdata]]></children>
        <children/>

    </element>
</root>
